An photogram industrial 2
AdolfoNava/photogram-industrial pull request #1
Opened 2024-07-01 19:54 UTC by AdolfoNava

This is including both parts 1 and 2

2024-07-01 19:55 UTC, brvarner approved these changes
looks good brother!

2024-07-01 21:28 UTC, thierrychau requested changes
See below minor comments. Please let me know when you have made the changes. Let me resolve the conversations.

2024-07-01 21:28 UTC, thierrychau commented on app/models/comment.rb
> +  belongs_to :photo
Can you add a counter_cache?

2024-07-01 21:28 UTC, thierrychau commented on app/models/like.rb
> +  has_many :likes
A like has many likes???

2024-07-01 21:28 UTC, thierrychau commented on app/models/like.rb
> +  has_many :likes
Can you add a validation to make sure a user cannot like a photo more than once?

2024-07-01 21:28 UTC, thierrychau commented on app/models/user.rb
> +  has_many :sent_follow_requests, foreign_key: :sender_id, class_name: "FollowRequest"
We want to avoid getting a violation of the foreign key constraint when a user gets deleted. Can you add `dependent: :destroy` option here?

2024-07-01 21:28 UTC, thierrychau commented on app/models/user.rb
> +  #   has_many :accepted_sent_follow_requests, -> {where(status: "accepted")}, foreign_key: :sender_id, class_name: "FollowRequest"
deleted commented out code??

2024-07-01 21:28 UTC, thierrychau commented on app/models/user.rb
> +  #   has_many :accepted_received_follow_requests, -> {where(status: "accepted")}, foreign_key: :recipient_id, class_name: "FollowRequest"
delete commented out code

2024-07-02 14:08 UTC, thierrychau approved these changes
Looks great, good job. Good to merge. Thanks for the edits.

2024-07-02 15:42 UTC, merged